### ISSUE TITLE
Do not strip AWS Region of it's hyphens

### ISSUE THREAD

**Issue by duartefleming** [tlgs/aws-primordial#1]
In your cloud formation, you're defining **StrippedRegion,** which you had to implement using custom logic.

**AWS::Region** is a widely available global parameter that can be leveraged when needed by many services.

In a situation in which any kind of component wants to write to that S3 bucket, one can leverage the AWS region environment variable directly on the name of the bucket and not have to remember to implement the custom StrippedRegion logic again.

As a bonus, all regions have a consistent length when if comes to "-", all have what would be something like **"Continent-CardinalDirection-Number"**.

Even though [here](https://docs.aws.amazon.com/prescriptive-guidance/latest/defining-bucket-names-data-lakes/defining-bucket-names-data-lakes.pdf) one might see refereces to namings such as **"s3://anycompany-useast1-dev"** nowhere do they mention this, plus in the naming format, present in such guide, states  **"awsregion – The AWS Region (for example,
us-east-1, or sa-east-1)"**.

I'd argue, more often will your applications need to reference buckets for reading and writing, which can leverage the unstripped AWS region than any other reason AWS failed to disclose.

**Comment by tlgs** [comment]
I'm inclined to agree, though when referencing other buckets you should not be relying on piecing its name together through string concatenation; You should pass the full bucket name as a parameter or, as defined in CloudFormation best practices, [use cross-stack references to export shared resources](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html#cross-stack).

I guess I enjoyed the idea of being able to split on hyphens (`-`) and get the different logical components that define that bucket. With this proposal, the parsing becomes a little trickier.

And [while all regions follow a consistent naming pattern](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-regions), I can't find any guarantee that this won't change in the future (though I'll admit that it is very, very, very unlikely).

All in all, I think I'll follow your suggestion - it simplifies the CFN template and doesn't break anything. Indeed, my first iteration looked to follow the examples given in the document you linked.
