### ISSUE TITLE
Add application artifacts bucket

### ISSUE THREAD

**Issue by duartefleming** [tlgs/aws-primordial#2]
As a developer of serverless functions, I would like to store artifacts such as AWS Lambda packages, etc..
For this many solutions could be implemented, however, I have yet to find consensus or even some sight of consistency when dealing with Lambda functions and their respective storage, versioning and deployment management.

However, some simple solutions could be, without going into the "how":
- S3 bucket with versioning enabled
- S3 bucket without versioning enable (for cost reduction), but with the artifact names as the commit hashes (arguably not as elegant)

I'm not one to take references without a pinch of salt, specially since I've seen barbaric gross mistakes coming from AWS materials, however, here's one:
https://github.com/awsdocs/aws-lambda-developer-guide/tree/main/sample-apps/nodejs-apig

**Comment by tlgs** [comment]
Done in 6340523b4e7e3873da626c820843ec69f8a4215c, 6 days ago.

As for the bucket properties, I've gone with the default one for cost reduction, while allowing each application to decide on the structure and how to store its artifact objects.
